const hotels = [
  {
    "id": "H001",
    "name": "Hotel Sunshine",
    "roomType": "Deluxe",
    "availability": true,
    "city": "Delhi",
    "pricePerNight": 3200,
    "rating": 4.3,
    "amenities": ["WiFi", "AC", "Breakfast"],
    "reviews": 128
  },
  {
    "id": "H002",
    "name": "Grand Palace",
    "roomType": "Suite",
    "availability": false,
    "city": "Mumbai",
    "pricePerNight": 5400,
    "rating": 4.7,
    "amenities": ["WiFi", "Pool", "Gym"],
    "reviews": 215
  },
  {
    "id": "H003",
    "name": "Cozy Stay",
    "roomType": "Single",
    "availability": true,
    "city": "Bangalore",
    "pricePerNight": 1500,
    "rating": 3.9,
    "amenities": ["WiFi", "Parking"],
    "reviews": 76
  },
  {
    "id": "H004",
    "name": "Urban Nest",
    "roomType": "Double",
    "availability": true,
    "city": "Hyderabad",
    "pricePerNight": 2100,
    "rating": 4.1,
    "amenities": ["WiFi", "AC"],
    "reviews": 134
  },
  {
    "id": "H005",
    "name": "The Royal Inn",
    "roomType": "Suite",
    "availability": false,
    "city": "Chennai",
    "pricePerNight": 5000,
    "rating": 4.8,
    "amenities": ["WiFi", "Pool", "Spa"],
    "reviews": 312
  },
  {
    "id": "H006",
    "name": "Blue Lagoon",
    "roomType": "Deluxe",
    "availability": true,
    "city": "Goa",
    "pricePerNight": 3800,
    "rating": 4.5,
    "amenities": ["WiFi", "Beach Access", "Bar"],
    "reviews": 199
  },
  {
    "id": "H007",
    "name": "Mountain View",
    "roomType": "Suite",
    "availability": true,
    "city": "Manali",
    "pricePerNight": 4200,
    "rating": 4.6,
    "amenities": ["WiFi", "Heater", "Balcony"],
    "reviews": 148
  },
  {
    "id": "H008",
    "name": "Lakefront Hotel",
    "roomType": "Double",
    "availability": true,
    "city": "Udaipur",
    "pricePerNight": 3300,
    "rating": 4.4,
    "amenities": ["WiFi", "View", "AC"],
    "reviews": 183
  },
  {
    "id": "H009",
    "name": "Budget Inn",
    "roomType": "Single",
    "availability": false,
    "city": "Pune",
    "pricePerNight": 1200,
    "rating": 3.5,
    "amenities": ["WiFi"],
    "reviews": 45
  },
  {
    "id": "H010",
    "name": "Hilltop Residency",
    "roomType": "Suite",
    "availability": true,
    "city": "Shimla",
    "pricePerNight": 3900,
    "rating": 4.2,
    "amenities": ["WiFi", "Balcony", "Heater"],
    "reviews": 127
  },
  {
    "id": "H011",
    "name": "City Comfort",
    "roomType": "Double",
    "availability": true,
    "city": "Ahmedabad",
    "pricePerNight": 2500,
    "rating": 4.0,
    "amenities": ["WiFi", "AC", "Breakfast"],
    "reviews": 96
  },
  {
    "id": "H012",
    "name": "Seaside Resort",
    "roomType": "Deluxe",
    "availability": false,
    "city": "Kochi",
    "pricePerNight": 3600,
    "rating": 4.3,
    "amenities": ["WiFi", "Beach Access", "AC"],
    "reviews": 178
  },
  {
    "id": "H013",
    "name": "Heritage Palace",
    "roomType": "Suite",
    "availability": true,
    "city": "Jaipur",
    "pricePerNight": 4700,
    "rating": 4.9,
    "amenities": ["WiFi", "Spa", "Pool"],
    "reviews": 329
  },
  {
    "id": "H014",
    "name": "Forest Edge",
    "roomType": "Deluxe",
    "availability": true,
    "city": "Ooty",
    "pricePerNight": 2800,
    "rating": 4.1,
    "amenities": ["WiFi", "Garden", "Heater"],
    "reviews": 104
  },
  {
    "id": "H015",
    "name": "Metro Lodge",
    "roomType": "Single",
    "availability": false,
    "city": "Noida",
    "pricePerNight": 1700,
    "rating": 3.8,
    "amenities": ["WiFi", "AC"],
    "reviews": 57
  },
  {
    "id": "H016",
    "name": "Business Hub Hotel",
    "roomType": "Double",
    "availability": true,
    "city": "Gurgaon",
    "pricePerNight": 2900,
    "rating": 4.0,
    "amenities": ["WiFi", "Work Desk", "AC"],
    "reviews": 88
  },
  {
    "id": "H017",
    "name": "Desert Inn",
    "roomType": "Suite",
    "availability": false,
    "city": "Jaisalmer",
    "pricePerNight": 4400,
    "rating": 4.4,
    "amenities": ["WiFi", "AC", "Terrace"],
    "reviews": 101
  },
  {
    "id": "H018",
    "name": "Airport Residency",
    "roomType": "Double",
    "availability": true,
    "city": "Nagpur",
    "pricePerNight": 2200,
    "rating": 3.9,
    "amenities": ["WiFi", "Airport Shuttle"],
    "reviews": 70
  },
  {
    "id": "H019",
    "name": "Snow View Hotel",
    "roomType": "Suite",
    "availability": true,
    "city": "Nainital",
    "pricePerNight": 4000,
    "rating": 4.5,
    "amenities": ["WiFi", "Balcony", "Heater"],
    "reviews": 154
  },
  {
    "id": "H020",
    "name": "Royal Orchid",
    "roomType": "Deluxe",
    "availability": false,
    "city": "Lucknow",
    "pricePerNight": 3100,
    "rating": 4.2,
    "amenities": ["WiFi", "Spa", "Breakfast"],
    "reviews": 92
  },
  {
    "id": "H021",
    "name": "Valley Inn",
    "roomType": "Double",
    "availability": true,
    "city": "Darjeeling",
    "pricePerNight": 2700,
    "rating": 4.1,
    "amenities": ["WiFi", "View"],
    "reviews": 89
  },
  {
    "id": "H022",
    "name": "Cityscape Hotel",
    "roomType": "Single",
    "availability": false,
    "city": "Bhopal",
    "pricePerNight": 1400,
    "rating": 3.7,
    "amenities": ["WiFi"],
    "reviews": 49
  },
  {
    "id": "H023",
    "name": "Riverfront Inn",
    "roomType": "Deluxe",
    "availability": true,
    "city": "Haridwar",
    "pricePerNight": 2600,
    "rating": 4.3,
    "amenities": ["WiFi", "View", "AC"],
    "reviews": 113
  },
  {
    "id": "H024",
    "name": "Island Breeze",
    "roomType": "Suite",
    "availability": false,
    "city": "Port Blair",
    "pricePerNight": 4900,
    "rating": 4.6,
    "amenities": ["WiFi", "Beach", "Balcony"],
    "reviews": 167
  },
  {
    "id": "H025",
    "name": "Coral Inn",
    "roomType": "Double",
    "availability": true,
    "city": "Visakhapatnam",
    "pricePerNight": 2800,
    "rating": 4.0,
    "amenities": ["WiFi", "Breakfast"],
    "reviews": 74
  },
  {
    "id": "H026",
    "name": "The Cliff House",
    "roomType": "Suite",
    "availability": true,
    "city": "Munnar",
    "pricePerNight": 4600,
    "rating": 4.5,
    "amenities": ["WiFi", "Mountain View", "Balcony"],
    "reviews": 144
  },
  {
    "id": "H027",
    "name": "Urban Stay",
    "roomType": "Double",
    "availability": false,
    "city": "Ranchi",
    "pricePerNight": 2300,
    "rating": 3.9,
    "amenities": ["WiFi", "AC"],
    "reviews": 58
  },
  {
    "id": "H028",
    "name": "Woods Retreat",
    "roomType": "Deluxe",
    "availability": true,
    "city": "Dehradun",
    "pricePerNight": 2900,
    "rating": 4.2,
    "amenities": ["WiFi", "Forest View", "Breakfast"],
    "reviews": 93
  },
  {
    "id": "H029",
    "name": "Harbor View Hotel",
    "roomType": "Suite",
    "availability": true,
    "city": "Chandigarh",
    "pricePerNight": 3800,
    "rating": 4.3,
    "amenities": ["WiFi", "Lake View", "AC"],
    "reviews": 123
  },
  {
    "id": "H030",
    "name": "Comfort Tree",
    "roomType": "Single",
    "availability": true,
    "city": "Indore",
    "pricePerNight": 1600,
    "rating": 3.8,
    "amenities": ["WiFi", "AC"],
    "reviews": 63
  }
]
export default hotels